### ISSUE TITLE
Sprite flicker and layering issues

### ISSUE THREAD

**Issue by RestartMV** [kins-dev/rpgmaker-mv-pixi5#3]
I'm getting a massive amount of sprite flicker (and doodad flicker) after upgrading, particularly when I spawn events

Furthermore, every time it flickers it has issues with z-sorting, which increase progressively each time (so I start out with a bench on layer 5 in front of a bunch of bushes on layer 5, and each flicker causes the bushes to sort themselves in front of the bench).  

I'm wondering if maybe their y-coordinate is getting displaced, because moving my character sprite in front of the glitched bushes now also ends up with him being layered incorrectly (with the bush on top of his head).

**Comment by RestartMV** [comment]
before and after
https://i.imgur.com/1B839PA.jpg
https://i.imgur.com/nFUynYM.jpg

**Comment by kins-dev** [comment]
Sorry I had a major hardware failure, I've been trying to get things rebuilt again.  It might be a week or more before I can look at this.

**Comment by kins-dev** [comment]
Good news is I have a fix.

Apparently there was a different issue causing the shader tilemap to cut out, that's been fixed.  I'll have something up soon.

**Comment by kins-dev** [comment]
I think this is fixed now.
